# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box = "nritholtz/ubuntu-14.04.1"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.ssh.username = 'vagrant'

   config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.name = "Ubuntu"
   end
end
